import = ["/Users/planetbeldar/.config/alacritty/themes/rouge.toml"]
live_config_reload = true

[cursor]
blink_interval = 750
thickness = 0.2
unfocused_hollow = true
vi_mode_style = "Block"

[cursor.style]
blinking = "Always"
shape = "Beam"

[font]
size = 14.0

[font.bold]
style = "Extra Light"

[font.bold_italic]
style = "Extra Light Italic"

[font.italic]
style = "Thin Italic"

[font.normal]
family = "InputMono Nerd Font"
style = "Thin"

[[hints.enabled]]
command = "open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "Shift"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mode = "~Search"
mods = "Shift|Command"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "P"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Paste"
key = "P"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Escape"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|\"' ()[]{}<>\t"

[window]
decorations = "none"

[window.padding]
x = 5
y = 5
