#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# macOS
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off # macOS < 13
yabai -m rule --add app="^System Settings$" manage=off # macOS >= 13 (Ventura)
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Books$" title="^Books|General|Reading|Playback|Advanced$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Calendar$" manage=off
yabai -m rule --add app="^Disk Utility$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Font Book$" manage=off
yabai -m rule --add app="^Keychain Access$" manage=off
yabai -m rule --add app="^Notes$" manage=off
yabai -m rule --add app="^Preview$" manage=off
yabai -m rule --add app="^Safari$" title="^General|Tabs|AutoFill|Passwords|Search|Security|Privacy|Websites|Extensions|Advanced$" manage=off
yabai -m rule --add app="^Vimari$" manage=off
yabai -m rule --add app="^Messages$" manage=off
yabai -m rule --add app="^1Password$" manage=off

# third party
yabai -m rule --add app="^Battle.net$" manage=off
#yabai -m rule --add app="^Emacs$" title!="^[*]doom[*]*" manage=off
yabai -m rule --add app="^Firefox$" title="^Opening[ ].*$" manage=off
yabai -m rule --add app="^Inkscape$" manage=off
yabai -m rule --add app="^iOS App Signer$" manage=off
yabai -m rule --add app="^Microsoft AutoUpdate$" manage=off
yabai -m rule --add app="^NoMachine$" manage=off
yabai -m rule --add app="^QMK Toolbox$" manage=off
yabai -m rule --add app="^Signal$" title="^Signal Desktop Preferences$" manage=off
yabai -m rule --add app="^Sonos$" manage=off
yabai -m rule --add app="^VMware Fusion$" manage=off
yabai -m rule --add app="^Tunnelblick$" manage=off
yabai -m rule --add app="^DataGrip$" manage=off
yabai -m rule --add app="^Tuple$" manage=off
yabai -m rule --add app="^[dD][bB]eaver.*$" manage=off
yabai -m rule --add app="^TablePlus$" manage=off
yabai -m rule --add app="^Cursr$" manage=off
yabai -m rule --add app="^OpenVPN Connect$" manage=off

# show digital colour meter topmost and on all spaces
yabai -m rule --add app="^Digital Colou?r Meter$" sticky=on manage=off

# work
yabai -m rule --add app="^Safari$" title="^Sign in - Google Accounts$" manage=off
yabai -m rule --add app="^IntelliJ IDEA" title!="( - )" manage=off
yabai -m rule --add app="^WebStorm" manage="off"

# rougez        active/normal   0xff775759 / 0xff172030
# wilmersdorf   active/normal   0xff575a77 / 0xff1f2024
# global settings
yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_topmost               off            \
    window_shadow                on             \
    window_animation_duration    0.05           \
    window_animation_frame_rate  120            \
    window_opacity_duration      0.0            \
    active_window_opacity        0.97           \
    normal_window_opacity        0.94           \
    window_opacity               on             \
    insert_feedback_color        0xffd75f5f     \
    active_window_border_color   0xff775759     \
    normal_window_border_color   0xff555555     \
    window_border_width          3              \
    window_border_radius         12             \
    window_border_blur           off            \
    window_border_hidpi          on             \
    window_border                off            \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  12             \
    bottom_padding               12             \
    left_padding                 12             \
    right_padding                12             \
    window_gap                   06             \
    layout                       bsp            \
    mouse_modifier               cmd            \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap           \
    debug_output                 off

echo "yabai configuration loaded.."
