#!/usr/bin/env nix-shell
#! nix-shell -i bash -p nix-prefetch jq

latest_release=$(curl --silent https://api.github.com/repos/ryanoasis/nerd-fonts/releases/latest)
glyphs=$(curl --silent  https://api.github.com/repos/ryanoasis/nerd-fonts/contents/src/glyphs)

version=$(jq -r '.tag_name' <<< "$latest_release")
dirname="$(dirname "$0")"

output_files="$dirname/files.nix"
output_version="$dirname/version.nix"

warning=$'### Generated by update script.\n\n'
echo -e "${warning}\""${version#v}"\"" > $output_version

echo Using version "$version"

printf '%s{\n' "$warning" > $output_files

while
    read -r path
    read -r url
do
    [[ $path != *" "* ]] && printf '  "%s" = "%s";\n' "${path}" "$(nix-prefetch-url "$url")" | tee -a $output_files
done < <(jq -r '.[] | .path, .download_url' <<< "$glyphs")

printf '}\n' >> $output_files
